package com.jejakteknisi.mesh
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.net.wifi.p2p.*;import android.os.Build;import android.media.*;import kotlinx.coroutines.*;import java.io.*;import java.net.*;import java.util.concurrent.atomic.AtomicBoolean
class WifiDirectEngine(private val c:Context){private val m=c.getSystemService(Context.WIFI_P2P_SERVICE) as WifiP2pManager;private val ch=m.initialize(c,c.mainLooper(),null);private val run=AtomicBoolean();private val sc=CoroutineScope(SupervisorJob()+Dispatchers.IO);private var r:BroadcastReceiver?=null;private var ss:ServerSocket?=null;@Volatile private var s:Socket?=null;private var ar:AudioRecord?=null;private var at:AudioTrack?=null;@Volatile var status="Menyiapkan Wi-Fi Direct...";private set;var onStatus:((String)->Unit)?=null;private fun st(x:String){status=x;onStatus?.invoke(x)};private fun ok()=Build.VERSION.SDK_INT<33||c.checkSelfPermission(Manifest.permission.NEARBY_WIFI_DEVICES)==PackageManager.PERMISSION_GRANTED
fun start(){if(run.getAndSet(true))return;reg();st("Mencari HP melalui Wi-Fi Direct...");disc();sc.launch{delay(1000);connectToFirstPeer()}}
private fun reg(){if(r!=null)return;r=object:BroadcastReceiver(){override fun onReceive(x:Context,i:Intent){when(i.action){WifiP2pManager.WIFI_P2P_CONNECTION_CHANGED_ACTION->info();WifiP2pManager.WIFI_P2P_STATE_CHANGED_ACTION->if(i.getIntExtra(WifiP2pManager.EXTRA_WIFI_STATE,-1)==WifiP2pManager.WIFI_P2P_STATE_ENABLED)disc()}}};c.registerReceiver(r,IntentFilter().apply{addAction(WifiP2pManager.WIFI_P2P_CONNECTION_CHANGED_ACTION);addAction(WifiP2pManager.WIFI_P2P_STATE_CHANGED_ACTION);addAction(WifiP2pManager.WIFI_P2P_PEERS_CHANGED_ACTION)})}
private fun disc(){if(!run.get()||!ok())return;try{m.discoverPeers(ch,object:WifiP2pManager.ActionListener{override fun onSuccess(){};override fun onFailure(x:Int){sc.launch{delay(1200);disc()}}})}catch(_:Exception){st("Izin Nearby Devices diperlukan")}}
fun connectToFirstPeer(){if(!run.get()||!ok())return;try{m.requestPeers(ch){l->val p=l.deviceList.firstOrNull()?:run{st("Menunggu HP kedua...");sc.launch{delay(1000);disc();connectToFirstPeer()}};if(p!=null){val q=WifiP2pConfig().apply{deviceAddress=p.deviceAddress;wps.setup=WpsInfo.PBC};m.connect(ch,q,object:WifiP2pManager.ActionListener{override fun onSuccess(){st("Menghubungkan...")};override fun onFailure(x:Int){sc.launch{delay(900);disc();connectToFirstPeer()}}})}}}catch(_:Exception){}}
private fun info(){if(!run.get()||!ok())return;try{m.requestConnectionInfo(ch){i->if(i.groupFormed){if(i.isGroupOwner)server() else i.groupOwnerAddress?.let{client(it)}}}}catch(_:Exception){}}
private fun server(){if(ss?.isClosed==false)return;sc.launch{try{ss=ServerSocket(45454);st("Menunggu HP kedua...");install(ss!!.accept())}catch(_:Exception){if(run.get()){delay(500);server()}}}}
private fun client(h:InetAddress){if(s?.isClosed==false)return;sc.launch{try{val x=Socket();x.tcpNoDelay=true;x.keepAlive=true;x.connect(InetSocketAddress(h,45454),2000);install(x)}catch(_:Exception){if(run.get()){delay(700);info()}}}}
@Synchronized private fun install(x:Socket){if(!run.get()||s?.isClosed==false){try{x.close()}catch(_:Exception){};return};s=x;st("🟢 TERHUBUNG — Wi-Fi Direct");audio(x)}
private fun audio(x:Socket){val ci=AudioRecord.getMinBufferSize(16000,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT);val co=AudioTrack.getMinBufferSize(16000,AudioFormat.CHANNEL_OUT_MONO,AudioFormat.ENCODING_PCM_16BIT);if(ci<=0||co<=0){st("Audio tidak didukung");return};ar=AudioRecord(MediaRecorder.AudioSource.VOICE_COMMUNICATION,16000,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,ci*2);at=AudioTrack.Builder().setAudioAttributes(AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_VOICE_COMMUNICATION).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build()).setAudioFormat(AudioFormat.Builder().setSampleRate(16000).setEncoding(AudioFormat.ENCODING_PCM_16BIT).setChannelMask(AudioFormat.CHANNEL_OUT_MONO).build()).setBufferSizeInBytes(co*2).setTransferMode(AudioTrack.MODE_STREAM).build();at?.play();sc.launch{try{val o=DataOutputStream(BufferedOutputStream(x.getOutputStream()));val b=ByteArray(640);ar?.startRecording();while(run.get()&&x===s&&!x.isClosed){val n=ar?.read(b,0,b.size)?:-1;if(n>0){o.writeInt(n);o.write(b,0,n);o.flush()}}}catch(_:Exception){discX(x)}};sc.launch{try{val i=DataInputStream(BufferedInputStream(x.getInputStream()));while(run.get()&&x===s&&!x.isClosed){val n=i.readInt();if(n !in 1..4096)throw IOException();val b=ByteArray(n);i.readFully(b);at?.write(b,0,n)}}catch(_:Exception){discX(x)}}}
private fun discX(x:Socket){if(s!==x)return;try{x.close()}catch(_:Exception){};s=null;try{ar?.stop()}catch(_:Exception){};try{at?.pause()}catch(_:Exception){};if(run.get()){st("🟡 Putus — mencari HP lagi...");sc.launch{delay(400);disc();delay(400);connectToFirstPeer()}}}
fun stop(){if(!run.getAndSet(false))return;try{r?.let{c.unregisterReceiver(it)}}catch(_:Exception){};r=null;try{s?.close();ss?.close()}catch(_:Exception){};try{ar?.stop();ar?.release();at?.stop();at?.release()}catch(_:Exception){};s=null}}
